import os
from google.adk import Agent
from google import genai
from dotenv import load_dotenv

load_dotenv(dotenv_path="../.env")

GCP_PROJECT_ID = os.environ.get("GCP_PROJECT_ID", "your-project-id")
GCP_LOCATION = os.environ.get("GCP_LOCATION", "global")
MANAGED_AGENT_ID = f"projects/{GCP_PROJECT_ID}/locations/{GCP_LOCATION}/agents/neo4j-managed-agent"

# 2. Native ADK Environment Configuration
os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "true"
os.environ["GOOGLE_CLOUD_PROJECT"] = GCP_PROJECT_ID
os.environ["GOOGLE_CLOUD_LOCATION"] = GCP_LOCATION

def query_managed_agent(user_prompt: str) -> str:
    """
    Forwards the user query directly to the secure backend Vertex AI Managed Agent
    using the verified streaming chunk architecture.

    Args:
        user_prompt: The raw text string entered by the user.

    Returns:
        The finalized text response generated by the serverless sandbox.
    """
    try:
        client = genai.Client(
            vertexai=True,
            project=GCP_PROJECT_ID,
            location=GCP_LOCATION,
        )

        stream = client.interactions.create(
            agent=MANAGED_AGENT_ID,
            input=user_prompt,
            stream=True,
            background=True,
            store=True
        )

        output_chunks = []
        for event in stream:
            event_type = getattr(event, "event_type", None) or event.get("event_type")
            if event_type == "step.delta":
                delta = getattr(event, "delta", None) or event.get("delta", {})
                if (getattr(delta, "type", None) or delta.get("type")) == "text":
                    text_chunk = getattr(delta, "text", "") or delta.get("text", "")
                    output_chunks.append(text_chunk)

        return "".join(output_chunks) if output_chunks else "No text response returned from backend."

    except Exception as e:
        return f"Proxy connection failure addressing backend engine: {str(e)}"

# 3. Instantiate the ADK Agent
root_agent = Agent(
    name="neo4j_platform_proxy",
    model="gemini-3.5-flash",
    instruction="""
    You are a strict, transparent pass-through proxy. Your only function is to forward the user's
    exact query to the query_managed_agent tool and report its output directly to the interface.
    """,
    tools=[query_managed_agent]
)