#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

command -v azd >/dev/null || {
  echo "Missing azd. Install: https://learn.microsoft.com/azure/developer/azure-developer-cli/install-azd"
  exit 1
}

shared_env="$(cd .. && pwd)/.env"

# Demo defaults (match .env.sample). Overridden below by the existing shared
# .env (if any) and then by this folder's local .env.
neo4j_uri="neo4j+s://demo.neo4jlabs.com:7687"
neo4j_database="companies"
neo4j_username="companies"
neo4j_password="companies"

foundry_resource_group=""
foundry_account_name=""
foundry_project_name=""
foundry_project_endpoint=""
foundry_model_deployment_name="gpt-4o-mini"
neo4j_mcp_connection_name=""

read_kv_file() {
  local file="$1"
  [ -f "$file" ] || return 0
  while IFS='=' read -r key value; do
    key="$(echo "$key" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    value="$(echo "${value:-}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    if [ -z "$key" ] || [[ "$key" == \#* ]]; then
      continue
    fi

    case "$key" in
      NEO4J_URI)                     [ -n "$value" ] && neo4j_uri="$value" ;;
      NEO4J_DATABASE)                [ -n "$value" ] && neo4j_database="$value" ;;
      NEO4J_USERNAME)                [ -n "$value" ] && neo4j_username="$value" ;;
      NEO4J_PASSWORD)                [ -n "$value" ] && neo4j_password="$value" ;;
      FOUNDRY_RESOURCE_GROUP)        [ -n "$value" ] && foundry_resource_group="$value" ;;
      FOUNDRY_ACCOUNT_NAME)          [ -n "$value" ] && foundry_account_name="$value" ;;
      FOUNDRY_PROJECT_NAME)          [ -n "$value" ] && foundry_project_name="$value" ;;
      FOUNDRY_PROJECT_ENDPOINT)      [ -n "$value" ] && foundry_project_endpoint="$value" ;;
      FOUNDRY_MODEL_DEPLOYMENT_NAME) [ -n "$value" ] && foundry_model_deployment_name="$value" ;;
      NEO4J_MCP_CONNECTION_NAME)     [ -n "$value" ] && neo4j_mcp_connection_name="$value" ;;
    esac
  done < "$file"
}

# Order: existing shared .env, then local infra .env (wins for any key it sets).
read_kv_file "$shared_env"
read_kv_file ".env"

# Forward local infra .env values into the azd environment so deployment
# parameters reach the Bicep. azd up itself prompts for AZURE_ENV_NAME, the
# subscription, and AZURE_LOCATION.
if [ -f ".env" ]; then
  while IFS='=' read -r key value; do
    key="$(echo "$key" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    value="$(echo "${value:-}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    if [ -z "$key" ] || [[ "$key" == \#* ]] || [ -z "$value" ]; then
      continue
    fi
    azd env set "$key" "$value" >/dev/null
  done < ".env"
fi

# Helper for safely reading values back out of the azd env after deploy.
azd_get() {
  local out
  if out="$(azd env get-value "$1" 2>/dev/null)" && [[ "$out" != ERROR:* ]]; then
    printf '%s' "$out"
  fi
}

# The Foundry opt-in prompt runs as an azd preprovision hook
# (hooks/preprovision.sh) so it happens after azd has created the env.
azd up "$@"

# Read deployed values back from the azd env. Empty when Foundry was disabled.
endpoint="$(azd_get mcpEndpoint)"
foundry_rg_out="$(azd_get foundryResourceGroup)"
foundry_account_out="$(azd_get foundryAccountName)"
foundry_project_out="$(azd_get foundryProjectName)"
foundry_project_endpoint_out="$(azd_get foundryProjectEndpoint)"
foundry_model_out="$(azd_get foundryModelDeploymentName)"
azure_subscription_id="$(azd_get AZURE_SUBSCRIPTION_ID)"
azure_tenant_id="$(azd_get AZURE_TENANT_ID)"
if command -v az >/dev/null; then
  [ -z "$azure_subscription_id" ] && azure_subscription_id="$(az account show --query id -o tsv 2>/dev/null || true)"
  if [ -z "$azure_tenant_id" ] && [ -n "$azure_subscription_id" ]; then
    azure_tenant_id="$(az account show --subscription "$azure_subscription_id" --query tenantId -o tsv 2>/dev/null || true)"
  fi
fi

[ -n "$foundry_rg_out" ]               && foundry_resource_group="$foundry_rg_out"
[ -n "$foundry_account_out" ]          && foundry_account_name="$foundry_account_out"
[ -n "$foundry_project_out" ]          && foundry_project_name="$foundry_project_out"
[ -n "$foundry_project_endpoint_out" ] && foundry_project_endpoint="$foundry_project_endpoint_out"
[ -n "$foundry_model_out" ]            && foundry_model_deployment_name="$foundry_model_out"

# Write microsoft-foundry/.env so every example script in this section can
# source the same file.
cat > "$shared_env" <<EOF
# Auto-generated by microsoft-foundry/infra/deploy.sh.
# Re-run deploy.sh to refresh the deployed values; non-empty values you set
# here are preserved across runs.
#
# Examples authenticate to Foundry via 'az login' — AzureCliCredential
# pinned to AZURE_TENANT_ID below. No Foundry tokens or keys live here.

# Neo4j connection.
NEO4J_URI=${neo4j_uri}
NEO4J_DATABASE=${neo4j_database}
NEO4J_USERNAME=${neo4j_username}
NEO4J_PASSWORD=${neo4j_password}

# Neo4j MCP server (deployed).
NEO4J_MCP_ENDPOINT=${endpoint}

# Microsoft Foundry project. Auto-filled when deploy.sh provisions Foundry;
# blank if you opted out — set them yourself in that case to point examples
# at your existing Foundry project.
AZURE_SUBSCRIPTION_ID=${azure_subscription_id}
AZURE_TENANT_ID=${azure_tenant_id}
FOUNDRY_RESOURCE_GROUP=${foundry_resource_group}
FOUNDRY_ACCOUNT_NAME=${foundry_account_name}
FOUNDRY_PROJECT_NAME=${foundry_project_name}
FOUNDRY_PROJECT_ENDPOINT=${foundry_project_endpoint}
FOUNDRY_MODEL_DEPLOYMENT_NAME=${foundry_model_deployment_name}

# Neo4j MCP project connection name. Set this manually after creating the
# connection in the Foundry portal — see microsoft-foundry/examples/mcp/README.md.
NEO4J_MCP_CONNECTION_NAME=${neo4j_mcp_connection_name}
EOF

cat <<EOF

Neo4j MCP server is ready.

Endpoint:
  ${endpoint}

Shared environment file:
  ${shared_env}

Smoke test:
  ./test-mcp.sh "${endpoint}"

EOF
