USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TERRAFORM_SVC;

CREATE USER IF NOT EXISTS TERRAFORM_SVC
    TYPE = SERVICE
    COMMENT = "Service user for Terraforming Snowflake"
    DEFAULT_ROLE = TERRAFORM_SVC
    RSA_PUBLIC_KEY = "<your-public-key>";

GRANT ROLE TERRAFORM_SVC TO USER TERRAFORM_SVC;

GRANT USAGE ON WAREHOUSE DEFAULT_WH TO ROLE TERRAFORM_SVC;
GRANT ROLE SYSADMIN TO ROLE TERRAFORM_SVC;
GRANT ROLE SECURITYADMIN TO ROLE TERRAFORM_SVC;
GRANT ROLE ACCOUNTADMIN TO ROLE TERRAFORM_SVC;
